FROM golang:1.16 as builder

RUN mkdir /app

COPY . /app

WORKDIR /app
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o hw_app_golang .

FROM scratch

COPY --from=builder /app/hw_app_golang /

CMD ["/hw_app_golang"]
